version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - db_data:/app/gospend_backend
    environment:
      - DJANGO_SETTINGS_MODULE=gospend_backend.settings
      - DEBUG=1
    command: >
      sh -c "if [ ! -f /app/gospend_backend/db.sqlite3 ]; then
               python gospend_backend/manage.py migrate;
             fi &&
             python gospend_backend/manage.py runserver 0.0.0.0:8000"

  nginx:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html

volumes:
  db_data: 