version: '3.8'

services:
  web:
    build: .
    restart: unless-stopped
    volumes:
      - .:/app
      - db_data:/app/gospend_backend
      - static_volume:/app/static
    environment:
      - DJANGO_SETTINGS_MODULE=gospend_backend.settings
      - DEBUG=0
      - ALLOWED_HOSTS=yourdomain.com,www.yourdomain.com
      - SECRET_KEY=your-secret-key-here
    command: >
      sh -c "if [ ! -f /app/gospend_backend/db.sqlite3 ]; then
               python gospend_backend/manage.py migrate;
             fi &&
             python gospend_backend/manage.py collectstatic --noinput &&
             python gospend_backend/manage.py runserver 0.0.0.0:8000"

  nginx:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - .:/usr/share/nginx/html
      - static_volume:/app/static

volumes:
  db_data:
  static_volume: 