FROM nginx:alpine

COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
COPY *.html /usr/share/nginx/html/
COPY *.css /usr/share/nginx/html/
COPY *.webp /usr/share/nginx/html/
COPY *.png /usr/share/nginx/html/ 